### ISSUE TITLE
Definition of modal verbs in IETF RFC 2119 (developer_guide.md)

### ISSUE THREAD

**Issue by ProkhorZ** [monero-project/kovri-docs#100]
This one sentence in the Code of Conduct is a challenge for translators:

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119.

[That's RFC 2119 of the Internet Engineering Task Force](https://tools.ietf.org/html/rfc2119).

The most important purpose of RFC 2119 is to specify that rules containing the words MUST, SHALL or REQUIRED are compulsory, while rules containing the words SHOULD or RECOMMENDED can be ignored when there are valid reasons to make an exception.

Our German translation refers to an [unofficial German translation of RFC 2119](https://github.com/adfinis-sygroup/2119). That's a reasonable solution if one is available, but I'd prefer a different solution: the translation should define which words in the translation are equivalent to MUST/SHALL etc. in RFC 2119.

Other existing translations are suboptimal. The French version simply translates the text literally. The Russian text keeps the capitalized words in English, which is correct but not useful. The Italian translation invites the reader to compare the English source text to RFC 2119. And in the Spanish translation of contributing.md, the word 'no' appears:

> no deben ser interpretadas como esta descrito en el RFC 2119

Based on my passive knowledge of the language of Cervantes, I conclude that this means the opposite of the source text. And `esta` should be spelled `está`, by the way.

I propose that existing translations are updated during or after updates.

**Comment by ProkhorZ** [comment]
For example, the type of localization I'm proposing is the following text for French (not sure about the Dutch translation for 'should' yet):

> Les mots clé "DOIT", "EXIGE" et "DEVRA", dans le présent document sont à interpréter comme "MUST" dans la RFC 2119, "NE DOIT PAS" et "NE DEVRA PAS" comme "MUST NOT", "DEVRAIT" et "RECOMMANDÉ" comme "SHOULD", "NE DEVRAIT PAS" comme "SHOULD NOT" et "PEUT" et "FACULTATIF" comme "MAY".

There are only five categories in RFC 2119, so not all synonyms need to be mentioned in English. And of course, we MUST translate these terms consistently in the rest of the Code of Conduct. 

I couldn't translate a whole page to French, but it looks like the existing translations *DEVRAIT* for *SHALL* and *DEVRA* for *SHOULD* are the wrong way around. And in Danish, *SKAL* is used for both *SHALL* and *SHOULD*, so that the reader doesn't see the difference between obligatory rules and recommendations. There's a reason why these terms are defined. Please check your translations.

Paging translators: @erciccione @el00ruobuob @cryptobench @monerorus @ordtrogen @rodolfo912 @woodyjon @cryptochangements34

**Comment by Josexv1** [comment]
About the Spanish translation, there's a PR with the fixed words. I'm trying to get it finish ASAP.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-docs/issues/102 for details.
