### ISSUE TITLE
Update FreeBSD 11 docs

### ISSUE THREAD

**Issue by noloader** [monero-project/kovri-docs#40]
The `README.md` states:

> ##FreeBSD 11
> 
> Required dependencies:
> 
> ```
> sudo pkg install git cmake gmake clang36 boost-libs openssl
> ```

I found I needed `boost-all` for asio; `boost-libs` was not enough. I also found I needed `cpp-netlib`.

At [related issue 562](https://github.com/weidai11/cryptopp/issues/562#issuecomment-361436598), @anonimal stated  `cpp-netlib` should not be needed. Maybe CMake is having trouble finding the library in-tree on FreeBSD.

**Comment by anonimal** [comment]
>I found I needed boost-all for asio; boost-libs was not enough. I also found I needed cpp-netlib.

JFTR: I *cannot* reproduce this issue. I just today downloaded a fresh FreeBSD image from https://download.freebsd.org/ftp/releases/VM-IMAGES/11.1-RELEASE/amd64/Latest/ and used the current build instructions. Successful build.

@noloader which image are you using?

**Comment by noloader** [comment]
> which image are you using?

FreeBSD 10.3.

The steps for me were:

1. Fork your Kovri
2. `git clone --recursive https://github.com/noloader/kovri.git`
3. `cd kovri`
4. `mkdir build`
5. `cd build`
6. `cmake -DCMAKE_CC_COMPILER=clang38 CMAKE_CXX_COMPILER=clang++38 ../`

**Comment by anonimal** [comment]
Oh, well the dependencies (cpp-netlib + cryptopp) must first be built. You can do that manually or have our [Makefile wrapper](https://github.com/monero-project/kovri/blob/master/Makefile) do it for you. If you want to tweak dependency build settings, it may be easier instead to adjust the Makefile as needed. If not, cpp-netlib uses CMake so you'll have to do the `mkdir ... cd build ... cmake ...` thing too.

Once the dependencies are built, the remaining build should go smoothly.

**Comment by anonimal** [comment]
Note: exporting `CC` and `CXX` will be caught by CMake, so I usually do something like:

```bash
$ gmake CC=clang38 CXX=clang++38 tests
```

which handles dependency building as well (as do all the Makefile targets).
