### ISSUE TITLE
Move building guide to kovri repo README

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-docs#47]
This will make the kovri repo README larger but from there we can hack away / condense the info.

**Comment by anonimal** [comment]
We should have translations of the kovri repo README anyway. @rehrar Perhaps this will be a good time to get the translation team involved.

**Comment by erciccione** [comment]
I think we should keep it simple and just add the translations in the same README file, maybe addinga small TOC at the beginning to let people know what languages are availabel. Let me know when we can start working on this so i can update the instructions for translators on taiga

**Comment by anonimal** [comment]
Hi @erciccione, sorry, I had merged the kovri-docs PR/closed this issue before seeing that you commented. If we need to reopen this issue, please let me know.

>Let me know when we can start working on this so i can update the instructions for translators on taiga

https://github.com/monero-project/kovri/pull/886 has been merged. You can start whenever you'd like.

**Comment by erciccione** [comment]
Instructions updated. They can be found here: https://taiga.getmonero.org/project/erciccione-monero-localization/wiki/translating-kovri-website
