### ISSUE TITLE
English layout changed, translations/reorganization needed for remaining languages

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-docs#51]
The building guide has been removed and build instructions moved to https://github.com/monero-project/kovri/blob/master/README.md. Other files/data have been moved into `user_guide.md` and `developer_guide.md` and include some minor changes.

Also, as discussed here, https://github.com/monero-project/kovri-docs/issues/47#issuecomment-393842837, now that the build instructions are in the kovri README, we'll need to have a clear plan on how to handle translating the kovri README. This wouldn't be a website effort, the issue is about translating the kovri README either within the kovri repo or here. Input needed.

Ping @erciccione.

**Comment by erciccione** [comment]
My suggestion is either to make a small TOC with the languages available at the beginning of the README and add the translations in the same file, or make different README in different languages and link to them from the main README file. I don't have a strong preference here, but maybe the first one is better since the README is not too verbose and mainly links to existent user guides

**Comment by anonimal** [comment]
I like the ideas. How about a TOC with links to other README languages that are hosted in kovri-docs? If we keep everything in one README, or even have another README, there will be too many PRs to the kovri repo that are unrelated to code and will clutter the log. Does that make sense? Any better solutions?

**Comment by erciccione** [comment]
That sounds like a good solution to me. If that's good for you i can start to work on it

**Comment by anonimal** [comment]
Yes, thank you.

**Comment by erciccione** [comment]
TOC created (monero-project/kovri#906) and Italian translation submitted (monero-project/kovri-docs#53)
@anonimal  please review

**Comment by anonimal** [comment]
Reviewed.

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-docs/issues/102 for details.
