### ISSUE TITLE
Dead link to Twitter in the FAQ

### ISSUE THREAD

**Issue by ProkhorZ** [monero-project/kovri-docs#60]
Hey @anonimal, the Kovri FAQ still links to your old twitter username. Do you want to update it yourself?

I was going to make a pull request for all languages where it occurs (not in Spanish and Italian), but then I noticed the French translation is being updated at the moment.

**Comment by anonimal** [comment]
Hi @ProkhorZ, thank you for pointing this out. I'll make the change a.s.a.p.
