### ISSUE TITLE
i18n: update non-English documentation

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-docs#8]
Before https://github.com/monero-project/kovri-site/issues/6 was resolved, all non-English documentation was based off of outdated English documentation. The outdated documentation was pulled from the kovri repo (before kovri-docs was created) and used statically within kovri-site, and then the translations were based off of those.

@Dridou @Vanchesss @MoroccanMalinois @erciccione @Josexv1 @serhack @jonathancross: the English docs are now up-to-date. Could you do translation updates? Any updates would be greatly appreciated!

**Comment by serhack** [comment]
Okay, I'm going to translate that @erciccione can you start? I will review

**Comment by erciccione** [comment]
@serhack Already started, #9 ready for reviews

**Comment by anonimal** [comment]
Wow 😮, thank you both for doing that so quickly @serhack @erciccione.

**Comment by Josexv1** [comment]
Will check Spanish translation.

**Comment by anonimal** [comment]
FYI, #10 will be merged soon.

**Comment by serhack** [comment]
Your welcome @anonimal

**Comment by ProkhorZ** [comment]
FYI: I started working on a Dutch translation today.

**Comment by erciccione** [comment]
Great to hear that @ProkhorZ . If you need any info/support come chat on #monero-translations (irc-freenode, riot/matrix, slack)

**Comment by erciccione** [comment]
Docs have been updated again and all languages need to be checked. Contact me [on reddit](https://www.reddit.com/message/compose/?to=ErCiccione) or on `#monero-translations` if you need info/support

**Comment by anonimal** [comment]
A million thanks to @erciccione and everyone involved in the monero translation team. Taiga has officially replaced this open issue.
