### ISSUE TITLE
Links in the FAQ

### ISSUE THREAD

**Issue by ProkhorZ** [monero-project/kovri-docs#81]
The FAQ still refers to the Contributing Guide for reporting bugs (line 139). Shouldn't this be the Developer Guide? And the README link in line 138 should be moved to `/i8n/en/`.

**Comment by rehrar** [comment]
The README link on line 138 resolves not to a kovri-docs README but to the README on the kovri repo itself. Are you saying we should switch it to the kovri-docs README? In en it's README-TEMPLATE.

Working on the other one. Should be resolved ASAP.

**Comment by anonimal** [comment]
>And the README link in line 138 should be moved to /i8n/en/.

This line? ```- Vulnerabilities: see our [README](https://github.com/monero-project/kovri/blob/master/README.md)``` That can stay there because it points to the correct document.

**Comment by anonimal** [comment]
Resolved in #83.
