### ISSUE TITLE
User guide needs clarification: $ ./kovri 

### ISSUE THREAD

**Issue by ordtrogen** [monero-project/kovri-docs#84]
user_guide.md says

![image](https://user-images.githubusercontent.com/15184875/43228234-3e5eeb1e-9061-11e8-8418-83cc555fcd4e.png)

But if you've followed the make and install instruction on the kovri main page, the "make install" will have installed kovri to the ~/bin/ folder, so the instruction doesn't work unless you've already "cd ~/bin" which isn't mentioned anywhere.

I have no suggestion to make. If the user_guide.md said "$ ~/bin/kovri --help" instead, I guess it would be platform dependent (Linux)?

**Comment by anonimal** [comment]
Resolved in #85.
