### ISSUE TITLE
i18n translations for new Monero Guide

### ISSUE THREAD

**Issue by anonimal** [monero-project/kovri-docs#92]
https://github.com/monero-project/kovri-docs/blob/master/i18n/en/monero_guide.md

**Comment by erciccione** [comment]
Will open tasks on Taiga for our translators

**Comment by anonimal** [comment]
NOTICE: THIS ISSUE HAS BEEN MOVED TO GitLab. Please continue the discussion there. See https://github.com/monero-project/kovri-docs/issues/102 for details.
